server:
  address: 192.168.1.6
  port: 8081

spring:
  data:
    mongodb:
      authentication-database: admin
      username: admin # (default->rootuser)
      password: password # (default->rootpass)
      database: test
      auto-index-creation: true
      port: 27017              #(default->27017)
      host: localhost              #(default->localhost)
            
 